export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL =
  '/assets/blog/meta/meta-image.png'
export const BLOG_NAME = 'Bhavesh Patil @iambhvsh'
export const KEYWORDS = 'starter, blog, next.js, template, iambhvsh, bhavesh, patil, bhavesh patil, sanjay, sanjay patil'
export const DESCRIPTION = 'Exploring the intersection of technology, case studies, and politics, our blog delves into the latest trends, insightful analyses, and thought-provoking discussions to provide readers with a comprehensive understanding of todays dynamic landscape.'
export const AUTHOR = 'iambhvsh'
export const LANG = 'en-CA'
export const GITHUB_REPO = 'https://github.com/iambhvsh'
